### PR TITLE
Allow getAccountFollowing to follow all pages of return by parsing the Link header

### LINKED ISSUE #1444: Handle Link header for next/prev following list for Mastodon
The documentation for Mastodn's [`api/v1/accounts/:id/following`](https://docs.joinmastodon.org/methods/accounts/) endpoint says

> Because the ID of follow relationships is not generally used or provided with any API calls, an HTTP Link header is used instead to indicate next and previous pages. You will have to parse this header yourself to extract the paging URLs.

And there's an example:
```
Link: <https://mastodon.social/api/v1/accounts/1/followers?limit=2&max_id=7628164>; rel="next", <https://mastodon.social/api/v1/accounts/1/followers?limit=2&since_id=7628165>; rel="prev"
```

So after I call Megalodon's `getAccountFollowing` function, I I can get the Response's `headers` and extract the `Link` header and parse it (there's this nice parser: https://www.npmjs.com/package/parse-link-header that works well), but if I make a request to the `next` URL, I'll have to do all the error handling myself, which is annoying.

Would you be interested in a PR that parses this `Link` header and fetches each `next` link to build a *full* list of follows?

Thanks!

### PR DESCRIPTION
**Pull request by fasiha**
Fixes #1444.

Instead of a new function, I tried adding just an extra option to `getAccountFollowing` which makes it iterate over the paginated responses till it has all the follows list by following each page's response's `Link` header. Tested locally and it works 😄.

I had to add an extra argument to the client's `get` function because the `Link` header returns a URL with a fully qualified domain name whereas `get` assumes an absolute domain. Is this ok? Another way to do this is, this feature could make sure the `Link` header starts with the same domain as the Megalodon interface's `baseUrl` and then *remove* that `baseUrl` from the `Link` header URL? Let me know if you prefer this approach and I can make the change.

### CODE REVIEW

**Comment by fasiha** [comment]
Sorry for the delay @h3poteto, I will complete this this week! I'm using the code in the PR and it's working well. I sort of wish there was a simple way for it to tell the parent app what it's progress is, but I think for now this is fine. Thanks for your great advice!

**Comment by fasiha** [comment]
@h3poteto updated per your helpful advice! Tested with the following, which gets a server and token from environment variable and helps me visually see that the `sleep_ms` is roughly doing its job:
```js
var meg = require('megalodon');

async function main(sleep_ms) {
  var gen = meg.default;
  var m = gen('mastodon', process.env.MASTODON, process.env.TOKEN)

  var tic = Date.now();

  var f = await m.getAccountFollowing('45008');
  console.log(f.data.length, (Date.now() - tic), 'ms');
  f = await m.getAccountFollowing('45008', {get_all: true, sleep_ms});
  console.log(f.data.length, (Date.now() - tic), 'ms');

  tic = Date.now();
  var f = await m.getAccountFollowers('45008');
  console.log(f.data.length, (Date.now() - tic), 'ms');
  f = await m.getAccountFollowers('45008', {get_all: true, sleep_ms});
  console.log(f.data.length, (Date.now() - tic), 'ms');
}

(async function() {
  console.log('with no sleep/delay');
  await main(undefined);
  console.log('sleeping before following Link header');
  await main(2000);
})();
```

The above script outputs for me (148 follows, 451 followers):
```
with no sleep/delay
40 1516 ms
148 6257 ms
40 1427 ms
451 16326 ms
sleeping before following Link header
40 1267 ms
148 11862 ms
40 1153 ms
451 39004 ms
```

Hope this is ok!

**Review by h3poteto — APPROVED** [review]
good

**Comment by fasiha** [comment]
@h3poteto would it be possible for you to publish a new version to npmjs?

Alternatively, do you know how I can install the TypeScript package with npm from GitHub? When I try `npm i megalodon@https://github.com/h3poteto/megalodon`, my imports break, perhaps because:
```sh
ls node_modules/megalodon
CODEOWNERS  LICENSE.txt  README.md  docs  example  megalodon  migration_guide.md  package.json
```

**Comment by h3poteto** [comment]
Oh, I'm sorry.
Released https://github.com/h3poteto/megalodon/releases/tag/v4.1.2

**Pull request merged**
