### PR TITLE
Build with swc instead of tsc

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
swc build: 42.63ms
tsc build: 7150ms

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Should be good now

**Comment by ThatOneCalculator** [comment]
Just noticed I accidentally committing my yarn error log... 😅

**Comment by h3poteto** [comment]
In the first place, did you feel that the build was slow?

And is there any reason why you choose swc over esbuild?

**Comment by ThatOneCalculator** [comment]
Yeah, the build was pretty slow for hot reloading and testing. Esbuild is also fairly slow in comparison to swc.

**Comment by ThatOneCalculator** [comment]
@h3poteto rebased, and tests pass. It's hard to find a friendica server with good uptime :woozy_face:

**Review by h3poteto — APPROVED** [review]
OK, I will try it.

**Comment by ThatOneCalculator** [comment]
It seems that the issue of migrating from CommonJS to ESModules should be resolved alongside this

**Pull request merged**
